from typing import Optional
from dataclasses import dataclass, field

from ..record_base import BaseRecord


@dataclass
class CardDataRecord(BaseRecord):
    cardDataId: Optional[int] = field(default=0)
    cardMstId: Optional[int] = field(default=0)
    userId: Optional[int] = field(default=0)
    level: Optional[int] = field(default=1)
    maxLevel: Optional[int] = field(default=1)
    exp: Optional[int] = field(default=0)
    levelupExp: Optional[int] = field(default=0)
    frontSkillMstId: Optional[int] = field(default=0)
    frontSkillLevel: Optional[int] = field(default=1)
    frontSkillExp: Optional[int] = field(default=0)
    frontSkillMaxLevel: Optional[int] = field(default=15)
    backSkillMstId: Optional[int] = field(default=0)
    backSkillLevel: Optional[int] = field(default=1)
    backSkillExp: Optional[int] = field(default=0)
    backSkillMaxLevel: Optional[int] = field(default=15)
    autoSkillMstId: Optional[int] = field(default=0)
    autoSkillLevel: Optional[int] = field(default=1)
    autoSkillExp: Optional[int] = field(default=0)
    autoSkillMaxLevel: Optional[int] = field(default=15)
    questSkillMstId: Optional[int] = field(default=0)
    questSkillLevel: Optional[int] = field(default=1)
    questSkillExp: Optional[int] = field(default=0)
    questSkillMaxLevel: Optional[int] = field(default=15)
    limitBreakSkillMstId: Optional[int] = field(default=0)
    protectorSkillMstId: Optional[int] = field(default=0)
    protectorSkillLevel: Optional[int] = field(default=1)
    protectorSkillExp: Optional[int] = field(default=0)
    protectorSkillMaxLevel: Optional[int] = field(default=15)
    plusAttack: Optional[int] = field(default=0)
    plusMagicAttack: Optional[int] = field(default=0)
    plusDefence: Optional[int] = field(default=0)
    plusMagicDefence: Optional[int] = field(default=0)
    limitBreakCount: Optional[int] = field(default=0)
    status: Optional[int] = field(default=0)
    isDeck: Optional[bool] = field(default=False)
    isProtect: Optional[bool] = field(default=False)
    isLeaderCard: Optional[bool] = field(default=False)
    isNightmareSearch: Optional[bool] = field(default=False)
    roomItemDataId: Optional[int] = field(default=0)
    createdTime: Optional[str] = field(default="")
    updatedTime: Optional[str] = field(default=None)
    cardExpPercent: Optional[int] = field(default=0)
    attack: Optional[int] = field(default=0)
    defence: Optional[int] = field(default=0)
    magicAttack: Optional[int] = field(default=0)
    magicDefence: Optional[int] = field(default=0)
    frontSkillExpPercent: Optional[int] = field(default=0)
    backSkillExpPercent: Optional[int] = field(default=0)
    autoSkillExpPercent: Optional[int] = field(default=0)
    questSkillExpPercent: Optional[int] = field(default=0)
    protectorSkillExpPercent: Optional[int] = field(default=0)
    baseMergeCost: Optional[int] = field(default=0)
    baseLimitBreakCost: Optional[int] = field(default=0)
    openedStoryStep: Optional[int] = field(default=1)
