from typing import Optional
from dataclasses import dataclass, field

from ..record_base import BaseRecord


@dataclass
class DeckDataRecord(BaseRecord):
    deckDataId: Optional[int] = field(default=0)
    userId: Optional[int] = field(default=0)
    deckName: Optional[str] = field(default="")
    characterDataId: Optional[int] = field(default=0)
    multipleCharacterMstId: Optional[int] = field(default=0)
    deckType: Optional[int] = field(default=0)
    isGvg: Optional[bool] = field(default=False)
    isGvgSubSet: Optional[bool] = field(default=False)
    isQuest: Optional[bool] = field(default=False)
    isRecommend: Optional[bool] = field(default=False)
    deckCardNum: Optional[int] = field(default=0)
    maxDeckCardNum: Optional[int] = field(default=0)
    fireCardNum: Optional[int] = field(default=0)
    waterCardNum: Optional[int] = field(default=0)
    windCardNum: Optional[int] = field(default=0)
    darkCardNum: Optional[int] = field(default=0)
    lightCardNum: Optional[int] = field(default=0)
    totalDeckCost: Optional[int] = field(default=0)
    totalAttack: Optional[int] = field(default=0)
    vsFireTotalAttack: Optional[int] = field(default=0)
    vsWaterTotalAttack: Optional[int] = field(default=0)
    vsWindTotalAttack: Optional[int] = field(default=0)
    totalDefence: Optional[int] = field(default=0)
    vsFireTotalDefence: Optional[int] = field(default=0)
    vsWaterTotalDefence: Optional[int] = field(default=0)
    vsWindTotalDefence: Optional[int] = field(default=0)
    totalPower: Optional[int] = field(default=0)
    attackTotalPower: Optional[int] = field(default=0)
    magicAttackTotalPower: Optional[int] = field(default=0)
    defenceTotalPower: Optional[int] = field(default=0)
    magicDefenceTotalPower: Optional[int] = field(default=0)
    maxHp: Optional[int] = field(default=0)
    isDeleted: Optional[bool] = field(default=False)
    createdTime: Optional[str] = field(default="")
    updatedTime: Optional[str] = field(default="")
    index: Optional[int] = field(default=0)
    totalPowerColosseumWinBonus: Optional[int] = field(default=0)
    attackTotalPowerColosseumWinBonus: Optional[int] = field(default=0)
    magicAttackTotalPowerColosseumWinBonus: Optional[int] = field(default=0)
    defenceTotalPowerColosseumWinBonus: Optional[int] = field(default=0)
    magicDefenceTotalPowerColosseumWinBonus: Optional[int] = field(default=0)
    totalAttackOnlyMainWeapon: Optional[int] = field(default=0)
    totalMagicAttackOnlyMainWeapon: Optional[int] = field(default=0)
    totalDefenceOnlyMainWeapon: Optional[int] = field(default=0)
    totalMagicDefenceOnlyMainWeapon: Optional[int] = field(default=0)
