from typing import Optional
from dataclasses import dataclass, field
from ..record_base import BaseRecord


@dataclass
class UserMiniTutorialDataRecord(BaseRecord):
    userId: Optional[int] = None
    t01: Optional[bool] = field(default=False)
    t02: Optional[bool] = field(default=False)
    t03: Optional[bool] = field(default=False)
    t04: Optional[bool] = field(default=False)
    t05: Optional[bool] = field(default=False)
    t06: Optional[bool] = field(default=False)
    t07: Optional[bool] = field(default=False)
    t08: Optional[bool] = field(default=False)
    t09: Optional[bool] = field(default=False)
    t10: Optional[bool] = field(default=False)
    t11: Optional[bool] = field(default=False)
    t12: Optional[bool] = field(default=False)
    t13: Optional[bool] = field(default=False)
    t14: Optional[bool] = field(default=False)
    t15: Optional[bool] = field(default=False)
    t16: Optional[bool] = field(default=False)
    t17: Optional[bool] = field(default=False)
    t18: Optional[bool] = field(default=False)
    t19: Optional[bool] = field(default=False)
    t20: Optional[bool] = field(default=False)
    t21: Optional[bool] = field(default=False)
    t22: Optional[bool] = field(default=False)
    t23: Optional[bool] = field(default=False)
    t24: Optional[bool] = field(default=False)
    t25: Optional[bool] = field(default=False)
    t26: Optional[bool] = field(default=False)
    t27: Optional[bool] = field(default=False)
    t28: Optional[bool] = field(default=False)
    t29: Optional[bool] = field(default=False)
    t30: Optional[bool] = field(default=False)
    t31: Optional[bool] = field(default=False)
    t32: Optional[bool] = field(default=False)
    t33: Optional[bool] = field(default=False)
    t34: Optional[bool] = field(default=False)
    # t35: Optional[bool] = field(default=False)
    t36: Optional[bool] = field(default=False)
    t37: Optional[bool] = field(default=False)
    t38: Optional[bool] = field(default=False)
    t39: Optional[bool] = field(default=False)
    t40: Optional[bool] = field(default=False)
    t41: Optional[bool] = field(default=False)
    t42: Optional[bool] = field(default=False)
    t43: Optional[bool] = field(default=False)
    t44: Optional[bool] = field(default=False)
    t45: Optional[bool] = field(default=False)
    t46: Optional[bool] = field(default=False)
    t47: Optional[bool] = field(default=False)
    # t48: Optional[bool] = field(default=False)
    t49: Optional[bool] = field(default=False)
    t50: Optional[bool] = field(default=False)
    # t51: Optional[bool] = field(default=False)
    t52: Optional[bool] = field(default=False)
    t53: Optional[bool] = field(default=False)
    t54: Optional[bool] = field(default=False)
    t55: Optional[bool] = field(default=False)
    # t56: Optional[bool] = field(default=False)
    t57: Optional[bool] = field(default=False)
    t58: Optional[bool] = field(default=False)
    t59: Optional[bool] = field(default=False)
    # t60: Optional[bool] = field(default=False)
    t61: Optional[bool] = field(default=False)
    t62: Optional[bool] = field(default=False)
    t63: Optional[bool] = field(default=False)
    t64: Optional[bool] = field(default=False)
    t65: Optional[bool] = field(default=False)
    # t66: Optional[bool] = field(default=False)
    t67: Optional[bool] = field(default=False)
    t68: Optional[bool] = field(default=False)
    # t69: Optional[bool] = field(default=False)
    # t70: Optional[bool] = field(default=False)
    # t71: Optional[bool] = field(default=False)
    t72: Optional[bool] = field(default=False)
    # t73: Optional[bool] = field(default=False)
    # t74: Optional[bool] = field(default=False)
    # t75: Optional[bool] = field(default=False)
    # t76: Optional[bool] = field(default=False)
    # t77: Optional[bool] = field(default=False)
    # t78: Optional[bool] = field(default=False)
    t79: Optional[bool] = field(default=False)
    t80: Optional[bool] = field(default=False)
    # t81: Optional[bool] = field(default=False)
    # t82: Optional[bool] = field(default=False)
    # t83: Optional[bool] = field(default=False)
    # t84: Optional[bool] = field(default=False)
    t85: Optional[bool] = field(default=False)
    # t86: Optional[bool] = field(default=False)
    # t87: Optional[bool] = field(default=False)
    t88: Optional[bool] = field(default=False)
    t89: Optional[bool] = field(default=False)
    t90: Optional[bool] = field(default=False)
    t91: Optional[bool] = field(default=False)
    # t92: Optional[bool] = field(default=False)
    t93: Optional[bool] = field(default=False)
    t94: Optional[bool] = field(default=False)
    # t95: Optional[bool] = field(default=False)
    # t96: Optional[bool] = field(default=False)
    # t97: Optional[bool] = field(default=False)
    t98: Optional[bool] = field(default=False)
    t99: Optional[bool] = field(default=False)
