from typing import Optional
from dataclasses import dataclass, field
from ..record_base import BaseRecord


@dataclass
class GuildDataRecord(BaseRecord):
    guildDataId: Optional[int] = field(default=None)
    guildName: Optional[str] = field(default=None)
    guildDescription: Optional[str] = field(default=None)
    guildMasterUserId: Optional[int] = field(default=None)
    maxMember: Optional[int] = field(default=None)
    joinMember: Optional[int] = field(default=None)
    guildExp: Optional[int] = field(default=None)
    guildLevel: Optional[int] = field(default=None)
    guildRank: Optional[int] = field(default=None)
    guildPoint: Optional[int] = field(default=None)
    gvgWin: Optional[int] = field(default=None)
    gvgLose: Optional[int] = field(default=None)
    gvgDraw: Optional[int] = field(default=None)
    gvgTimeType: Optional[int] = field(default=None)
    isStreamingPermission: Optional[bool] = field(default=None)
    isPublished: Optional[bool] = field(default=None)
    isStreaming: Optional[bool] = field(default=None)
    isRecording: Optional[bool] = field(default=None)
    beforeGvgTimeType: Optional[int] = field(default=None)
    isAutoAccept: Optional[bool] = field(default=None)
    isAutoUnionAccept: Optional[bool] = field(default=None)
    autoExpulsionType: Optional[int] = field(default=None)
    isGvgPushCall: Optional[bool] = field(default=None)
    gvgPushCallComment: Optional[str] = field(default=None)
    currentGuildTitleMstId: Optional[int] = field(default=None)
    subscriptionPowerType: Optional[int] = field(default=None)
    subscriptionGvgJoinType: Optional[int] = field(default=None)
    subscriptionActionType: Optional[int] = field(default=None)
    subscriptionStyleType: Optional[int] = field(default=None)
    subscriptionComment: Optional[str] = field(default=None)
    isRecruit: Optional[bool] = field(default=None)
    tacticsDescription: Optional[str] = field(default=None)
    favoriteAkbMember: Optional[int] = field(default=None)
    masterName: Optional[str] = field(default=None)
    masterLeaderCardMstId: Optional[int] = field(default=None)
    masterCharacterMstId: Optional[int] = field(default=None)
    ranking: Optional[int] = field(default=None)
    lastRank: Optional[int] = field(default=None)
    bannerMstId: Optional[int] = field(default=None)
    siegeHp: Optional[int] = field(default=None)
    siegeHpBonus: Optional[int] = field(default=None)
    createdTime: Optional[int] = field(default=None)
    countryCode: Optional[int] = field(default=None)
